"""ISO-4217 alphabetic currency codes accepted on extracted documents (authority:
ISO 4217 / SIX maintenance agency); static snapshot dated 2026-06-20.

Membership backs the currency validator in `_common.py`. Because extraction reads
real-world documents (not just the current instant), the set is the active codes
PLUS codes mid-transition between active and historic, so a recently-issued or
slightly-historical invoice is not falsely rejected:
- ANG and XCG (Netherlands Antillean guilder -> Caribbean guilder, 2025) both kept.
- VES and VED (Venezuela) both kept (both on SIX List One).
- BGN kept though Bulgaria is adopting EUR (pre-transition invoices still carry it).
- CHE and CHW (WIR Euro / WIR Franc) included: real List One codes used on Swiss B2B
  invoices, alongside CHF.

Deliberately excluded (not transactable document currencies): precious metals
XAU/XAG/XPT/XPD, the test code XTS, the no-currency code XXX, and fund/special codes
(XUA, XSU, XBA-XBD). Long-superseded codes are omitted in favour of their current
replacement (e.g. VEF->VES, MRO->MRU, STD->STN, BYR->BYN, SLL->SLE, ZWL->ZWG). The
real supranational currencies (XOF, XAF, XPF, XCD, XDR) are included.

This is a dated snapshot; a periodic ISO-4217 refresh is tracked as follow-up.
"""

from __future__ import annotations

ISO_4217_ALPHA: frozenset[str] = frozenset(
    {
        "AED",
        "AFN",
        "ALL",
        "AMD",
        "ANG",
        "AOA",
        "ARS",
        "AUD",
        "AWG",
        "AZN",
        "BAM",
        "BBD",
        "BDT",
        "BGN",
        "BHD",
        "BIF",
        "BMD",
        "BND",
        "BOB",
        "BRL",
        "BSD",
        "BTN",
        "BWP",
        "BYN",
        "BZD",
        "CAD",
        "CDF",
        "CHE",
        "CHF",
        "CHW",
        "CLP",
        "CNY",
        "COP",
        "CRC",
        "CUP",
        "CVE",
        "CZK",
        "DJF",
        "DKK",
        "DOP",
        "DZD",
        "EGP",
        "ERN",
        "ETB",
        "EUR",
        "FJD",
        "FKP",
        "GBP",
        "GEL",
        "GHS",
        "GIP",
        "GMD",
        "GNF",
        "GTQ",
        "GYD",
        "HKD",
        "HNL",
        "HTG",
        "HUF",
        "IDR",
        "ILS",
        "INR",
        "IQD",
        "IRR",
        "ISK",
        "JMD",
        "JOD",
        "JPY",
        "KES",
        "KGS",
        "KHR",
        "KMF",
        "KPW",
        "KRW",
        "KWD",
        "KYD",
        "KZT",
        "LAK",
        "LBP",
        "LKR",
        "LRD",
        "LSL",
        "LYD",
        "MAD",
        "MDL",
        "MGA",
        "MKD",
        "MMK",
        "MNT",
        "MOP",
        "MRU",
        "MUR",
        "MVR",
        "MWK",
        "MXN",
        "MYR",
        "MZN",
        "NAD",
        "NGN",
        "NIO",
        "NOK",
        "NPR",
        "NZD",
        "OMR",
        "PAB",
        "PEN",
        "PGK",
        "PHP",
        "PKR",
        "PLN",
        "PYG",
        "QAR",
        "RON",
        "RSD",
        "RUB",
        "RWF",
        "SAR",
        "SBD",
        "SCR",
        "SDG",
        "SEK",
        "SGD",
        "SHP",
        "SLE",
        "SOS",
        "SRD",
        "SSP",
        "STN",
        "SVC",
        "SYP",
        "SZL",
        "THB",
        "TJS",
        "TMT",
        "TND",
        "TOP",
        "TRY",
        "TTD",
        "TWD",
        "TZS",
        "UAH",
        "UGX",
        "USD",
        "UYU",
        "UZS",
        "VED",
        "VES",
        "VND",
        "VUV",
        "WST",
        "XAF",
        "XCD",
        "XCG",
        "XDR",
        "XOF",
        "XPF",
        "YER",
        "ZAR",
        "ZMW",
        "ZWG",
    }
)
